// Chemical concern levels based on EPA IRIS carcinogenicity classifications.
// Source: https://www.epa.gov/iris
// Classifications follow EPA's 2005 Guidelines for Carcinogen Risk Assessment.
//
// concern levels:
//   'high'   — "Carcinogenic to Humans" or "Likely to be Carcinogenic to Humans"
//   'medium' — "Suggestive Evidence of Carcinogenicity" or significant documented non-cancer health effects
//   'low'    — Inadequate/no evidence of carcinogenicity; limited health effects at typical exposures

export const CHEMICAL_INFO = {

  // ── CARCINOGENIC TO HUMANS ───────────────────────────────────────────────────
  'ARSENIC':                            { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'ARSENIC COMPOUNDS':                  { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'ARSENIC AND ARSENIC COMPOUNDS':      { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'ASBESTOS':                           { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'BENZENE':                            { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'BENZIDINE':                          { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'BERYLLIUM':                          { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'BERYLLIUM COMPOUNDS':                { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'CADMIUM':                            { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'CADMIUM COMPOUNDS':                  { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'CHROMIUM COMPOUNDS':                 { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'CHROMIUM AND CHROMIUM COMPOUNDS':    { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'CHROMIUM AND CHROMIUM COMPOUNDS(EXCEPT FOR CHROMITE ORE MINED IN THE TRANSVAAL REGION)':
                                        { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'CHROMIUM(VI)':                       { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'COKE OVEN EMISSIONS':                { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'DIOXIN AND DIOXIN-LIKE COMPOUNDS':   { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  '2,3,7,8-TETRACHLORODIBENZO-P-DIOXIN': { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'ETHYLENE OXIDE':                     { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'FORMALDEHYDE':                       { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  '1,3-BUTADIENE':                      { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'NICKEL COMPOUNDS':                   { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'NICKEL REFINERY DUST':               { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'NICKEL SUBSULFIDE':                  { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'NICKEL CARBONYL':                    { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'POLYCHLORINATED BIPHENYLS (PCBS)':   { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'POLYCHLORINATED BIPHENYLS':          { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'SULFURIC ACID':                      { concern: 'high', irisClassification: 'Carcinogenic to Humans (acid mists)' },
  'TRICHLOROETHYLENE':                  { concern: 'high', irisClassification: 'Carcinogenic to Humans' },
  'VINYL CHLORIDE':                     { concern: 'high', irisClassification: 'Carcinogenic to Humans' },

  // ── LIKELY TO BE CARCINOGENIC TO HUMANS ─────────────────────────────────────
  'ACRYLAMIDE':                         { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'ACRYLONITRILE':                      { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'BENZO[A]PYRENE':                     { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'BENZ[A]ANTHRACENE':                  { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'BENZO[B]FLUORANTHENE':               { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'BENZO[K]FLUORANTHENE':               { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'DIBENZ[A,H]ANTHRACENE':              { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'INDENO[1,2,3-CD]PYRENE':             { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'CARBON TETRACHLORIDE':               { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'CHLOROFORM':                         { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'DICHLOROMETHANE':                    { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'METHYLENE CHLORIDE':                 { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'DICHLOROMETHANE (METHYLENE CHLORIDE)': { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  '1,2-DIBROMOETHANE':                  { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  '1,4-DIOXANE':                        { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'ETHYLENE DIBROMIDE':                 { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'HEXACHLOROBENZENE':                  { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'HYDRAZINE':                          { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'HYDRAZINE/HYDRAZINE SULFATE':        { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'LEAD':                               { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'LEAD COMPOUNDS':                     { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'LEAD AND LEAD COMPOUNDS':            { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'NAPHTHALENE':                        { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'PERCHLOROETHYLENE':                  { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'TETRACHLOROETHYLENE':                { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'PROPYLENE OXIDE':                    { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'STYRENE':                            { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  '1,1,2,2-TETRACHLOROETHANE':          { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },
  'TOXAPHENE':                          { concern: 'high', irisClassification: 'Likely to be Carcinogenic to Humans' },

  // ── SUGGESTIVE EVIDENCE / SIGNIFICANT NON-CANCER HEALTH EFFECTS ─────────────
  'ACETALDEHYDE':                       { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'ACROLEIN':                           { concern: 'medium', irisClassification: 'Documented respiratory effects (EPA IRIS)' },
  'ANILINE':                            { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'AMMONIA':                            { concern: 'medium', irisClassification: 'Documented respiratory effects (EPA IRIS)' },
  'ANTIMONY':                           { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'ANTIMONY COMPOUNDS':                 { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'ATRAZINE':                           { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'BARIUM':                             { concern: 'medium', irisClassification: 'Documented cardiovascular effects (EPA IRIS)' },
  'BARIUM COMPOUNDS':                   { concern: 'medium', irisClassification: 'Documented cardiovascular effects (EPA IRIS)' },
  'CARBON DISULFIDE':                   { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'CHLORDANE':                          { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'CHLORINE':                           { concern: 'medium', irisClassification: 'Documented respiratory effects (EPA IRIS)' },
  'CHLOROPRENE':                        { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'COBALT':                             { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'COBALT COMPOUNDS':                   { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'CROTONALDEHYDE':                     { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'CYANIDE COMPOUNDS':                  { concern: 'medium', irisClassification: 'Documented acute toxicity (EPA IRIS)' },
  'DIBUTYL PHTHALATE':                  { concern: 'medium', irisClassification: 'Documented reproductive effects (EPA IRIS)' },
  'DIBUTYL PHTHALATE (DBP)':            { concern: 'medium', irisClassification: 'Documented reproductive effects (EPA IRIS)' },
  '1,2-DICHLOROBENZENE':                { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  '1,4-DICHLOROBENZENE':                { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  '1,2-DICHLOROETHANE':                 { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  '1,1-DICHLOROETHYLENE':               { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'DIELDRIN':                           { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'DI(2-ETHYLHEXYL) PHTHALATE':         { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'DI(2-ETHYLHEXYL)PHTHALATE (DEHP)':   { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'EPICHLOROHYDRIN':                    { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'ETHYLBENZENE':                       { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'FURAN':                              { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'HEXACHLOROBUTADIENE':                { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'HEXACHLOROCYCLOPENTADIENE':          { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'HEXACHLOROETHANE':                   { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'HYDROCHLORIC ACID':                  { concern: 'medium', irisClassification: 'Documented respiratory effects (EPA IRIS)' },
  'HYDROGEN CYANIDE':                   { concern: 'medium', irisClassification: 'Documented acute toxicity (EPA IRIS)' },
  'HYDROGEN CYANIDE AND CYANIDE SALTS': { concern: 'medium', irisClassification: 'Documented acute toxicity (EPA IRIS)' },
  'HYDROGEN SULFIDE':                   { concern: 'medium', irisClassification: 'Documented respiratory/neurological effects (EPA IRIS)' },
  'HYDROQUINONE':                       { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'ISOPHORONE':                         { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'MANGANESE':                          { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'MANGANESE COMPOUNDS':                { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'MERCURY':                            { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'MERCURY COMPOUNDS':                  { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'METHYLMERCURY':                      { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'METHYL CHLORIDE':                    { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'METHYL IODIDE':                      { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'NICKEL':                             { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'NICKEL, SOLUBLE SALTS':              { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'NITRATE COMPOUNDS':                  { concern: 'medium', irisClassification: 'Documented risk to infants via drinking water (EPA)' },
  'NITRATE COMPOUNDS (WATER DISSOCIABLE; REPORTABLE ONLY WHEN IN AQUEOUS SOLUTION)':
                                        { concern: 'medium', irisClassification: 'Documented risk to infants via drinking water (EPA)' },
  'NITROBENZENE':                       { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  '2-NITROPROPANE':                     { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'N-NITROSODIMETHYLAMINE':             { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'PENTACHLOROPHENOL':                  { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'PHTHALIC ANHYDRIDE':                 { concern: 'medium', irisClassification: 'Documented respiratory sensitization (EPA IRIS)' },
  'POLYCYCLIC AROMATIC COMPOUNDS':      { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'POLYCYCLIC AROMATIC HYDROCARBONS':   { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'PYRIDINE':                           { concern: 'medium', irisClassification: 'Suggestive Evidence of Carcinogenicity' },
  'SELENIUM':                           { concern: 'medium', irisClassification: 'Documented toxic effects at high exposures (EPA IRIS)' },
  'SELENIUM COMPOUNDS':                 { concern: 'medium', irisClassification: 'Documented toxic effects at high exposures (EPA IRIS)' },
  'THALLIUM':                           { concern: 'medium', irisClassification: 'Documented neurological/systemic effects (EPA IRIS)' },
  'THALLIUM COMPOUNDS':                 { concern: 'medium', irisClassification: 'Documented neurological/systemic effects (EPA IRIS)' },
  'TOLUENE':                            { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  '2,4-/2,6-TOLUENE DIISOCYANATE MIXTURE (TDI)':
                                        { concern: 'medium', irisClassification: 'Documented respiratory sensitization (EPA IRIS)' },
  'TOLUENE DIISOCYANATE':               { concern: 'medium', irisClassification: 'Documented respiratory sensitization (EPA IRIS)' },
  'VANADIUM (FUME OR DUST)':            { concern: 'medium', irisClassification: 'Documented respiratory effects (EPA IRIS)' },
  'VANADIUM COMPOUNDS':                 { concern: 'medium', irisClassification: 'Documented respiratory effects (EPA IRIS)' },
  'XYLENE':                             { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'XYLENES':                            { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },
  'XYLENES (MIXED ISOMERS)':            { concern: 'medium', irisClassification: 'Documented neurological effects (EPA IRIS)' },

  // ── LOW / INADEQUATE EVIDENCE ────────────────────────────────────────────────
  'ACETONE':                            { concern: 'low', irisClassification: 'Inadequate information (EPA IRIS)' },
  'ACETIC ACID':                        { concern: 'low', irisClassification: 'Inadequate information (EPA IRIS)' },
  'COPPER':                             { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'COPPER COMPOUNDS':                   { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'CYCLOHEXANE':                        { concern: 'low', irisClassification: 'Inadequate information (EPA IRIS)' },
  'ETHYLENE GLYCOL':                    { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'FORMIC ACID':                        { concern: 'low', irisClassification: 'Inadequate information (EPA IRIS)' },
  'GLYCOL ETHERS':                      { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'MALEIC ANHYDRIDE':                   { concern: 'low', irisClassification: 'Documented irritant effects; inadequate cancer data (EPA IRIS)' },
  'METHANOL':                           { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'N-HEXANE':                           { concern: 'low', irisClassification: 'Documented peripheral neuropathy; inadequate cancer data (EPA IRIS)' },
  'PHOSPHORIC ACID':                    { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'PROPYLENE GLYCOL':                   { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'SILVER':                             { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'SILVER COMPOUNDS':                   { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'SILVER AND SILVER COMPOUNDS':        { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'SULFUR DIOXIDE':                     { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  '1,1,1-TRICHLOROETHANE':              { concern: 'low', irisClassification: 'Inadequate information (EPA IRIS)' },
  'TRICHLOROFLUOROMETHANE':             { concern: 'low', irisClassification: 'Inadequate information (EPA IRIS)' },
  'UREA':                               { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'ZINC COMPOUNDS':                     { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
  'ZINC AND ZINC COMPOUNDS':            { concern: 'low', irisClassification: 'Limited health effects at typical exposures (EPA IRIS)' },
}

const CONCERN_LABEL = {
  high:   'High Concern',
  medium: 'Moderate Concern',
  low:    'Low Concern',
}

export function getChemicalInfo(name) {
  return CHEMICAL_INFO[name.toUpperCase()] ?? null
}

export function getConcernLabel(concern) {
  return CONCERN_LABEL[concern] ?? concern
}
